pre-commit:
  image: python:3
  stage: lint
  script:
    - pip install pre-commit packaging
    - pre-commit run --all-files --show-diff-on-failure
  artifacts:
    expire_in: 1 days
    paths:
      - docker-images/

.docker:
  image: docker:latest
  variables:
    GIT_STRATEGY: none
  services:
    - docker:19-dind
  before_script:
    - export IMAGE="ffmpeg:${VERSION}-${VARIANT:-ubuntu}"
  script:
    - docker build -t "${IMAGE}" --build-arg MAKEFLAGS="-j$(($(nproc) + 1))" docker-images/${VERSION}/${VARIANT}
    - docker images
  after_script:
    - docker run --rm ${IMAGE} -buildconf

include:
  - local: "docker-images/gitlab-ci.yml"
