sudo: required

language: bash
services: docker

env:
 - VERSION=3.2
 - VERSION=3.2 VARIANT=alpine
 - VERSION=3.2 VARIANT=centos
 - VERSION=3.1
 - VERSION=3.1 VARIANT=alpine
 - VERSION=3.1 VARIANT=centos
 - VERSION=3.0
 - VERSION=3.0 VARIANT=alpine
 - VERSION=3.0 VARIANT=centos
 - VERSION=2.8
 - VERSION=2.8 VARIANT=alpine
 - VERSION=2.8 VARIANT=centos

before_script:
  - env | sort
  - image="ffmpeg:${VERSION}-${VARIANT:-ubuntu}"

script:
  - docker build -t "${image}" ${VERSION}/${VARIANT}

after_script:
  - docker images
# vim:set et ts=2 sw=2:
