sudo: required

language: bash
services: docker

env:
 - VERSION=snapshot VARIANT=ubuntu
 - VERSION=snapshot VARIANT=alpine
 - VERSION=snapshot VARIANT=centos
 - VERSION=snapshot VARIANT=scratch
 - VERSION=snapshot VARIANT=vaapi
 - VERSION=4.1 VARIANT=ubuntu
 - VERSION=4.1 VARIANT=alpine
 - VERSION=4.1 VARIANT=centos
 - VERSION=4.1 VARIANT=scratch
 - VERSION=4.1 VARIANT=vaapi
 - VERSION=4.0 VARIANT=ubuntu
 - VERSION=4.0 VARIANT=alpine
 - VERSION=4.0 VARIANT=centos
 - VERSION=4.0 VARIANT=scratch
 - VERSION=4.0 VARIANT=vaapi
 - VERSION=3.4 VARIANT=ubuntu
 - VERSION=3.4 VARIANT=alpine
 - VERSION=3.4 VARIANT=centos
 - VERSION=3.4 VARIANT=scratch
 - VERSION=3.4 VARIANT=vaapi
 - VERSION=3.3 VARIANT=ubuntu
 - VERSION=3.3 VARIANT=alpine
 - VERSION=3.3 VARIANT=centos
 - VERSION=3.3 VARIANT=scratch
 - VERSION=3.3 VARIANT=vaapi
 - VERSION=3.2 VARIANT=ubuntu
 - VERSION=3.2 VARIANT=alpine
 - VERSION=3.2 VARIANT=centos
 - VERSION=3.2 VARIANT=scratch
 - VERSION=3.2 VARIANT=vaapi
 - VERSION=3.1 VARIANT=ubuntu
 - VERSION=3.1 VARIANT=alpine
 - VERSION=3.1 VARIANT=centos
 - VERSION=3.1 VARIANT=scratch
 - VERSION=3.1 VARIANT=vaapi
 - VERSION=3.0 VARIANT=ubuntu
 - VERSION=3.0 VARIANT=alpine
 - VERSION=3.0 VARIANT=centos
 - VERSION=3.0 VARIANT=scratch
 - VERSION=3.0 VARIANT=vaapi
 - VERSION=2.8 VARIANT=ubuntu
 - VERSION=2.8 VARIANT=alpine
 - VERSION=2.8 VARIANT=centos
 - VERSION=2.8 VARIANT=scratch
 - VERSION=2.8 VARIANT=vaapi

branches:
  only:
    - "master"

before_install:
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - sudo apt-get update
    - sudo apt-get -y install docker-ce

before_script:
  - env | sort
  - image="ffmpeg:${VERSION}-${VARIANT:-ubuntu}"

script:
  - docker build -t "${image}" --build-arg MAKEFLAGS="-j$(($(grep -c ^processor /proc/cpuinfo) + 1))" docker-images/${VERSION}/${VARIANT}
  - docker run --rm ${image} -buildconf

after_script:
  - docker images
# vim:set et ts=2 sw=2:
