language: bash
services: docker

env:
 - VERSION=2.8.7 VARIANT=centos
 - VERSION=2.8.7 VARIANT=ubuntu
 - VERSION=3.0.2 VARIANT=centos
 - VERSION=3.0.2 VARIANT=ubuntu
 - VERSION=3.1.2 VARIANT=centos
 - VERSION=3.1.2 VARIANT=ubuntu

before_script:
  - env | sort
  - image="ffmpeg:${VERSION}-${VARIANT}"

script:
  - docker build -t "${image}" ${VERSION}/${VARIANT}
after_script:

  - docker images
# vim:set et ts=2 sw=2:
