variables:
- group: videotoolsbuild-dockerhub
- name: DOCKER
  value: jrottenberg/ffmpeg

jobs:
- job: Build
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    maxParallel: 10
    matrix:
      snapshot_ubuntu:
        VERSION: snapshot
        VARIANT: ubuntu
      snapshot_alpine:
        VERSION: snapshot
        VARIANT: alpine
      snapshot_centos:
        VERSION: snapshot
        VARIANT: centos
      snapshot_scratch:
        VERSION: snapshot
        VARIANT: scratch
      snapshot_vaapi:
        VERSION: snapshot
        VARIANT: vaapi
      snapshot_nvidia:
        VERSION: snapshot
        VARIANT: nvidia
      4_2_1_ubuntu:
        VERSION: 4.2
        VARIANT: ubuntu
      4_2_1_alpine:
        VERSION: 4.2
        VARIANT: alpine
      4_2_1_centos:
        VERSION: 4.2
        VARIANT: centos
      4_2_1_scratch:
        VERSION: 4.2
        VARIANT: scratch
      4_2_1_vaapi:
        VERSION: 4.2
        VARIANT: vaapi
      4_2_1_nvidia:
        VERSION: 4.2
        VARIANT: nvidia
      4_1_4_ubuntu:
        VERSION: 4.1
        VARIANT: ubuntu
      4_1_4_alpine:
        VERSION: 4.1
        VARIANT: alpine
      4_1_4_centos:
        VERSION: 4.1
        VARIANT: centos
      4_1_4_scratch:
        VERSION: 4.1
        VARIANT: scratch
      4_1_4_vaapi:
        VERSION: 4.1
        VARIANT: vaapi
      4_1_4_nvidia:
        VERSION: 4.1
        VARIANT: nvidia
      4_0_5_ubuntu:
        VERSION: 4.0
        VARIANT: ubuntu
      4_0_5_alpine:
        VERSION: 4.0
        VARIANT: alpine
      4_0_5_centos:
        VERSION: 4.0
        VARIANT: centos
      4_0_5_scratch:
        VERSION: 4.0
        VARIANT: scratch
      4_0_5_vaapi:
        VERSION: 4.0
        VARIANT: vaapi
      4_0_5_nvidia:
        VERSION: 4.0
        VARIANT: nvidia
      3_4_6_ubuntu:
        VERSION: 3.4
        VARIANT: ubuntu
      3_4_6_alpine:
        VERSION: 3.4
        VARIANT: alpine
      3_4_6_centos:
        VERSION: 3.4
        VARIANT: centos
      3_4_6_scratch:
        VERSION: 3.4
        VARIANT: scratch
      3_4_6_vaapi:
        VERSION: 3.4
        VARIANT: vaapi
      3_4_6_nvidia:
        VERSION: 3.4
        VARIANT: nvidia
      3_3_9_ubuntu:
        VERSION: 3.3
        VARIANT: ubuntu
      3_3_9_alpine:
        VERSION: 3.3
        VARIANT: alpine
      3_3_9_centos:
        VERSION: 3.3
        VARIANT: centos
      3_3_9_scratch:
        VERSION: 3.3
        VARIANT: scratch
      3_3_9_vaapi:
        VERSION: 3.3
        VARIANT: vaapi
      3_3_9_nvidia:
        VERSION: 3.3
        VARIANT: nvidia
      3_2_14_ubuntu:
        VERSION: 3.2
        VARIANT: ubuntu
      3_2_14_alpine:
        VERSION: 3.2
        VARIANT: alpine
      3_2_14_centos:
        VERSION: 3.2
        VARIANT: centos
      3_2_14_scratch:
        VERSION: 3.2
        VARIANT: scratch
      3_2_14_vaapi:
        VERSION: 3.2
        VARIANT: vaapi
      3_2_14_nvidia:
        VERSION: 3.2
        VARIANT: nvidia
  steps:
  - bash: |
      docker build -t ${DOCKER}:${VERSION}-${VARIANT} --build-arg MAKEFLAGS="-j$(($(grep -c ^processor /proc/cpuinfo) + 1))" docker-images/${VERSION}/${VARIANT}
      docker run --rm ${DOCKER}:${VERSION}-${VARIANT} -buildconf
    displayName: Build docker image
  - bash: |
      docker login --username ${DOCKER_LOGIN} --password ${DOCKER_PASSWORD}
      docker push ${DOCKER}:${VERSION}-${VARIANT}
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Push docker image
    env:
      DOCKER_PASSWORD: $(docker.password)