variables:
- group: videotoolsbuild-dockerhub
- name: DOCKER
  value: jrottenberg/ffmpeg

jobs:
- job: Build
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    maxParallel: 10
    matrix:
      snapshot_ubuntu1604:
        VERSION: snapshot
        VARIANT: ubuntu1604
        PARENT: ubuntu
        ISPARENT: False
      snapshot_ubuntu1804:
        VERSION: snapshot
        VARIANT: ubuntu1804
        PARENT: ubuntu
        ISPARENT: True
      snapshot_alpine311:
        VERSION: snapshot
        VARIANT: alpine311
        PARENT: alpine
        ISPARENT: True
      snapshot_centos7:
        VERSION: snapshot
        VARIANT: centos7
        PARENT: centos
        ISPARENT: False
      snapshot_centos8:
        VERSION: snapshot
        VARIANT: centos8
        PARENT: centos
        ISPARENT: True
      snapshot_scratch311:
        VERSION: snapshot
        VARIANT: scratch311
        PARENT: scratch
        ISPARENT: True
      snapshot_vaapi1804:
        VERSION: snapshot
        VARIANT: vaapi1804
        PARENT: vaapi
        ISPARENT: True
      snapshot_nvidia1804:
        VERSION: snapshot
        VARIANT: nvidia1804
        PARENT: nvidia
        ISPARENT: True
      4_2_ubuntu1604:
        VERSION: 4.2
        VARIANT: ubuntu1604
        PARENT: ubuntu
        ISPARENT: False
      4_2_ubuntu1804:
        VERSION: 4.2
        VARIANT: ubuntu1804
        PARENT: ubuntu
        ISPARENT: True
      4_2_alpine311:
        VERSION: 4.2
        VARIANT: alpine311
        PARENT: alpine
        ISPARENT: True
      4_2_centos7:
        VERSION: 4.2
        VARIANT: centos7
        PARENT: centos
        ISPARENT: False
      4_2_centos8:
        VERSION: 4.2
        VARIANT: centos8
        PARENT: centos
        ISPARENT: True
      4_2_scratch311:
        VERSION: 4.2
        VARIANT: scratch311
        PARENT: scratch
        ISPARENT: True
      4_2_vaapi1804:
        VERSION: 4.2
        VARIANT: vaapi1804
        PARENT: vaapi
        ISPARENT: True
      4_2_nvidia1804:
        VERSION: 4.2
        VARIANT: nvidia1804
        PARENT: nvidia
        ISPARENT: True
      4_1_ubuntu1604:
        VERSION: 4.1
        VARIANT: ubuntu1604
        PARENT: ubuntu
        ISPARENT: False
      4_1_ubuntu1804:
        VERSION: 4.1
        VARIANT: ubuntu1804
        PARENT: ubuntu
        ISPARENT: True
      4_1_alpine311:
        VERSION: 4.1
        VARIANT: alpine311
        PARENT: alpine
        ISPARENT: True
      4_1_centos7:
        VERSION: 4.1
        VARIANT: centos7
        PARENT: centos
        ISPARENT: False
      4_1_centos8:
        VERSION: 4.1
        VARIANT: centos8
        PARENT: centos
        ISPARENT: True
      4_1_scratch311:
        VERSION: 4.1
        VARIANT: scratch311
        PARENT: scratch
        ISPARENT: True
      4_1_vaapi1804:
        VERSION: 4.1
        VARIANT: vaapi1804
        PARENT: vaapi
        ISPARENT: True
      4_1_nvidia1804:
        VERSION: 4.1
        VARIANT: nvidia1804
        PARENT: nvidia
        ISPARENT: True
      4_0_ubuntu1604:
        VERSION: 4.0
        VARIANT: ubuntu1604
        PARENT: ubuntu
        ISPARENT: False
      4_0_ubuntu1804:
        VERSION: 4.0
        VARIANT: ubuntu1804
        PARENT: ubuntu
        ISPARENT: True
      4_0_alpine311:
        VERSION: 4.0
        VARIANT: alpine311
        PARENT: alpine
        ISPARENT: True
      4_0_centos7:
        VERSION: 4.0
        VARIANT: centos7
        PARENT: centos
        ISPARENT: False
      4_0_centos8:
        VERSION: 4.0
        VARIANT: centos8
        PARENT: centos
        ISPARENT: True
      4_0_scratch311:
        VERSION: 4.0
        VARIANT: scratch311
        PARENT: scratch
        ISPARENT: True
      4_0_vaapi1804:
        VERSION: 4.0
        VARIANT: vaapi1804
        PARENT: vaapi
        ISPARENT: True
      4_0_nvidia1804:
        VERSION: 4.0
        VARIANT: nvidia1804
        PARENT: nvidia
        ISPARENT: True
      3_4_ubuntu1604:
        VERSION: 3.4
        VARIANT: ubuntu1604
        PARENT: ubuntu
        ISPARENT: False
      3_4_ubuntu1804:
        VERSION: 3.4
        VARIANT: ubuntu1804
        PARENT: ubuntu
        ISPARENT: True
      3_4_alpine311:
        VERSION: 3.4
        VARIANT: alpine311
        PARENT: alpine
        ISPARENT: True
      3_4_centos7:
        VERSION: 3.4
        VARIANT: centos7
        PARENT: centos
        ISPARENT: False
      3_4_centos8:
        VERSION: 3.4
        VARIANT: centos8
        PARENT: centos
        ISPARENT: True
      3_4_scratch311:
        VERSION: 3.4
        VARIANT: scratch311
        PARENT: scratch
        ISPARENT: True
      3_4_vaapi1804:
        VERSION: 3.4
        VARIANT: vaapi1804
        PARENT: vaapi
        ISPARENT: True
      3_4_nvidia1804:
        VERSION: 3.4
        VARIANT: nvidia1804
        PARENT: nvidia
        ISPARENT: True
      3_3_ubuntu1604:
        VERSION: 3.3
        VARIANT: ubuntu1604
        PARENT: ubuntu
        ISPARENT: False
      3_3_ubuntu1804:
        VERSION: 3.3
        VARIANT: ubuntu1804
        PARENT: ubuntu
        ISPARENT: True
      3_3_alpine311:
        VERSION: 3.3
        VARIANT: alpine311
        PARENT: alpine
        ISPARENT: True
      3_3_centos7:
        VERSION: 3.3
        VARIANT: centos7
        PARENT: centos
        ISPARENT: False
      3_3_centos8:
        VERSION: 3.3
        VARIANT: centos8
        PARENT: centos
        ISPARENT: True
      3_3_scratch311:
        VERSION: 3.3
        VARIANT: scratch311
        PARENT: scratch
        ISPARENT: True
      3_3_vaapi1804:
        VERSION: 3.3
        VARIANT: vaapi1804
        PARENT: vaapi
        ISPARENT: True
      3_3_nvidia1804:
        VERSION: 3.3
        VARIANT: nvidia1804
        PARENT: nvidia
        ISPARENT: True
      3_2_ubuntu1604:
        VERSION: 3.2
        VARIANT: ubuntu1604
        PARENT: ubuntu
        ISPARENT: True
      3_2_alpine38:
        VERSION: 3.2
        VARIANT: alpine38
        PARENT: alpine
        ISPARENT: True
      3_2_centos7:
        VERSION: 3.2
        VARIANT: centos7
        PARENT: centos
        ISPARENT: True
      3_2_scratch38:
        VERSION: 3.2
        VARIANT: scratch38
        PARENT: scratch
        ISPARENT: True
      3_2_vaapi1604:
        VERSION: 3.2
        VARIANT: vaapi1604
        PARENT: vaapi
        ISPARENT: True
      3_2_nvidia1604:
        VERSION: 3.2
        VARIANT: nvidia1604
        PARENT: nvidia
        ISPARENT: True
  steps:
  - bash: |
      docker build -t ${DOCKER}:${VERSION}-${VARIANT} --build-arg MAKEFLAGS="-j$(($(grep -c ^processor /proc/cpuinfo) + 1))" docker-images/${VERSION}/${VARIANT}
      # Create a uniquely tagged version of the container to avoid pulling a version that was already on docker hub
      docker tag ${DOCKER}:${VERSION}-${VARIANT} ${DOCKER}:${VERSION}-${VARIANT}-$(Build.BuildId)
      # Run -buildconf from the unique version we just tagged to make sure the build was ok
      docker run --rm ${DOCKER}:${VERSION}-${VARIANT}-$(Build.BuildId) -buildconf
    displayName: Build docker image
  - bash: |
      docker login --username ${DOCKER_LOGIN} --password ${DOCKER_PASSWORD}
      docker push ${DOCKER}:${VERSION}-${VARIANT}
<<<<<<< HEAD
      if [ "${ISPARENT}" == "True" ] && [ "${VARIANT}" != "${PARENT}" ]; then docker tag "${DOCKER}:${VERSION}-${VARIANT}" "${DOCKER}:${VERSION}-${PARENT}"; docker push "${DOCKER}:${VERSION}-${PARENT}"; fi
=======
      docker push ${DOCKER}:${SHORT_VERSION}-${VARIANT}
>>>>>>> after update.py
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Push docker image
    env:
      DOCKER_PASSWORD: $(docker.password)
